name: vuln-scan

on:
    schedule:
      - cron: '0 */24 * * *'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev

      - name: Installing Most the tools 
        run: |
           GO111MODULE=on go install -v  github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
           GO111MODULE=on go install -v  github.com/projectdiscovery/notify/cmd/notify@v0.0.2
        shell: bash
      - name: Checks for Sidekiq
        run: |
          nuclei -l output/all -etags ssl -es info  -retries 3  | notify -slack -slack-webhook-url  ${{ secrets.SLACK_TOKEN }}
 
